/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.databricks.spark.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class DoubleArray extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DoubleArray\",\"namespace\":\"com.databricks.spark.avro\",\"fields\":[{\"name\":\"value\",\"type\":{\"type\":\"array\",\"items\":\"double\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.List<java.lang.Double> value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public DoubleArray() {}

  /**
   * All-args constructor.
   */
  public DoubleArray(java.util.List<java.lang.Double> value) {
    this.value = value;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return value;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: value = (java.util.List<java.lang.Double>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'value' field.
   */
  public java.util.List<java.lang.Double> getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.util.List<java.lang.Double> value) {
    this.value = value;
  }

  /** Creates a new DoubleArray RecordBuilder */
  public static DoubleArray.Builder newBuilder() {
    return new DoubleArray.Builder();
  }
  
  /** Creates a new DoubleArray RecordBuilder by copying an existing Builder */
  public static DoubleArray.Builder newBuilder(DoubleArray.Builder other) {
    return new DoubleArray.Builder(other);
  }
  
  /** Creates a new DoubleArray RecordBuilder by copying an existing DoubleArray instance */
  public static DoubleArray.Builder newBuilder(DoubleArray other) {
    return new DoubleArray.Builder(other);
  }
  
  /**
   * RecordBuilder for DoubleArray instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DoubleArray>
    implements org.apache.avro.data.RecordBuilder<DoubleArray> {

    private java.util.List<java.lang.Double> value;

    /** Creates a new Builder */
    private Builder() {
      super(DoubleArray.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(DoubleArray.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.value)) {
        this.value = data().deepCopy(fields()[0].schema(), other.value);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing DoubleArray instance */
    private Builder(DoubleArray other) {
            super(DoubleArray.SCHEMA$);
      if (isValidValue(fields()[0], other.value)) {
        this.value = data().deepCopy(fields()[0].schema(), other.value);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'value' field */
    public java.util.List<java.lang.Double> getValue() {
      return value;
    }
    
    /** Sets the value of the 'value' field */
    public DoubleArray.Builder setValue(java.util.List<java.lang.Double> value) {
      validate(fields()[0], value);
      this.value = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'value' field has been set */
    public boolean hasValue() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'value' field */
    public DoubleArray.Builder clearValue() {
      value = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public DoubleArray build() {
      try {
        DoubleArray record = new DoubleArray();
        record.value = fieldSetFlags()[0] ? this.value : (java.util.List<java.lang.Double>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
