/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.databricks.spark.avro;

import org.apache.avro.Schema;

import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

@SuppressWarnings("all")
@org.apache.avro.specific.FixedSize(16)
@org.apache.avro.specific.AvroGenerated
public class SimpleFixed extends org.apache.avro.specific.SpecificFixed {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"fixed\",\"name\":\"SimpleFixed\",\"namespace\":\"com.databricks.spark.avro\",\"size\":16}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  
  /** Creates a new SimpleFixed */
  public SimpleFixed() {
    super();
  }
  
  /** Creates a new SimpleFixed with the given bytes */
  public SimpleFixed(byte[] bytes) {
    super(bytes);
  }

  public void writeExternal(ObjectOutput out) throws IOException {
    //
  }

  public void readExternal(ObjectInput in) throws IOException {
    //
  }

  public Schema getSchema() {
    return getClassSchema();
  }
}
